Python全栈/Flask框架/bbs/apps/front/models.py
# @ Time    : 2020/5/8 21:27
# @ Author  : JuRan


from exts import db
import shortuuid
from werkzeug.security import generate_password_hash, check_password_hash
import enum
from datetime import datetime
from markdown import markdown
import bleach



class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4


class FrontUser(db.Model):
    # FrontUser  front_user
    __tablename__ = 'front_user'
    # 安全 asdasd34rsdf  uuid  shortuuid
    id = db.Column(db.String(100), primary_key=True, default=shortuuid.uuid)
    telephone = db.Column(db.String(11), nullable=False, unique=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), unique=True)

    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signatrue = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.UNKNOW)

    join_time = db.Column(db.DateTime, default=datetime.now)


    def __init__(self, *args, **kwargs):
        if "password" in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop('password')

        # super(FrontUser, self).__init__(*args, **kwargs)
        super().__init__(*args, **kwargs)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        result = check_password_hash(self.password, raw_password)
        return result


class PostModel(db.Model):
    __tablename__ = 'post'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    content_html = db.Column(db.Text)
    create_time = db.Column(db.DateTime, default=datetime.now)

    board_id = db.Column(db.Integer, db.ForeignKey("cms_board.id"))
    author_id = db.Column(db.String(100), db.ForeignKey("front_user.id"))

    board = db.relationship("BoardModel", backref="posts")
    author = db.relationship("FrontUser", backref="posts")

    @staticmethod
    def on_changed_content(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p', 'img', 'video', 'div', 'iframe', 'p', 'br', 'span', 'hr', 'src', 'class']
        allowed_attrs = {'*': ['class'],
                         'a': ['href', 'rel'],
                         'img': ['src', 'alt']}
        target.content_html = bleach.linkify(bleach.clean(
            markdown(value, output_format='html'),
            tags=allowed_tags, strip=True, attributes=allowed_attrs))


db.event.listen(PostModel.content, 'set', PostModel.on_changed_content)

Python全栈/Flask框架/bbs/apps/front/forms.py
# @ Time    : 2020/5/8 21:27
# @ Author  : JuRan

from wtforms import Form, StringField, IntegerField, ValidationError
from wtforms.validators import Email, InputRequired, Length, EqualTo, Regexp
from utils import lgcache


class BaseForm(Form):
    def get_error(self):
        message = self.errors.popitem()[1][0]
        return message


class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message='请输入正确的手机号')])
    sms_captcha = StringField(validators=[Regexp(r'\w{4}', message='请输入正确的短信验证码')])
    username = StringField(validators=[Length(min=2, max=20, message='请输入正确的用户名')])
    password1 = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}', message='请输入正确的密码')])
    password2 = StringField(validators=[EqualTo('password1', message='两次密码输入不一致')])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}', message='请输入正确的验证码')])


    def validate_sms_captcha(self, field):
        telephone = self.telephone.data
        sms_captcha = self.sms_captcha.data

        # 从Redis中取验证码
        sms_captcha_redis = lgcache.redis_get(telephone)

        if not sms_captcha_redis or sms_captcha_redis.lower() != sms_captcha.lower():
            raise ValidationError(message='短信验证码错误')


    def validate_graph_captcha(self, field):
        graph_captcha = self.graph_captcha.data

        graph_captcha_redis = lgcache.redis_get(graph_captcha)

        if not graph_captcha_redis or graph_captcha_redis.lower() != graph_captcha.lower():
            raise ValidationError(message='图形验证码错误')



class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[345789]\d{9}', message='请输入正确的手机号')])
    password = StringField(validators=[Regexp(r'[0-9a-zA-Z_\.]{6,20}', message='请输入正确的密码')])
    remember = StringField(InputRequired())


class AddPostForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入标题')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id')])
    content = StringField(validators=[InputRequired(message='请输入内容')])

Python全栈/Flask框架/bbs/apps/front/__init__.py
# @ Time    : 2020/5/8 21:26
# @ Author  : JuRan

Python全栈/Flask框架/bbs/apps/front/views.py
# @ Time    : 2020/5/8 21:27
# @ Author  : JuRan
from flask import Blueprint, views, render_template, make_response, request, session, g, redirect, url_for
from utils.captcha import Captcha
from utils import lgcache, restful, safe_url
from io import BytesIO
from .forms import SignupForm, SigninForm, AddPostForm
from .models import FrontUser, PostModel
from apps.cms.models import BannerModel, BoardModel
from exts import db

from .decorators import login_required

front_bp = Blueprint("front", __name__)
from .hooks import before_request


@front_bp.route("/")
def index():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()
    board_id = request.args.get('board_id', type=int, default=None)

    posts = PostModel.query.all()


    context = {
        "banners": banners,
        "boards": boards,
        "current_board": board_id,
        "posts": posts
    }

    return render_template('front/front_index.html', **context)



@front_bp.route('/captcha/')
def graph_captcha():
    try:
        text, image = Captcha.gene_graph_captcha()
        lgcache.redis_set(text.lower(), text.lower())
        # BytesIO 字节流
        out = BytesIO()
        # 把图片保存在字节流中  并制定格式png
        image.save(out, 'png')
        # 文件流指针
        out.seek(0)
        resp = make_response(out.read())
        resp.content_type = 'image/png'
    except:
        return graph_captcha()
    return resp


@front_bp.route('/test/')
def test():
    return render_template('front/test.html')


class SignupView(views.MethodView):

    def get(self):
        # 在当前的页面  None
        # referrer  页面的跳转
        # http://127.0.0.1:5000/test/ => www.baidu.com
        # print(request.referrer)
        return_to = request.referrer
        # print(safe_url.is_safe_url(return_to))
        # is_safe_url 请求是否来自站内
        if return_to and return_to != request.url and safe_url.is_safe_url(return_to):
            # text, image = Captcha.gene_graph_captcha()
            # print(text)
            # print(image)
            return render_template("front/front_signup.html", return_to=return_to)
        else:
            return render_template('front/front_signup.html')


    def post(self):
        form = SignupForm(request.form)

        # 表单验证

        if form.validate():
            # 保存到数据库
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data

            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_errors(message=form.get_error())


class SigninView(views.MethodView):

    def get(self):
        # http://127.0.0.1:5000/signin/
        # print(request.url)  当前的URL地址
        return_to = request.referrer
        if return_to and return_to != request.url and safe_url.is_safe_url(return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')


    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data

            # user = FrontUser.query.filter(FrontUser.telephone == telephone).first()
            user = FrontUser.query.filter_by(telephone=telephone).first()

            if user and user.check_password(password):
                session['front_user_id'] = user.id
                if remember:
                    # 持久化
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_errors(message='手机号或者密码错误')

        else:
            return restful.params_errors(message=form.get_error())


class PostView(views.MethodView):

    decorators = [login_required]

    def get(self):
        boards = BoardModel.query.all()
        return render_template("front/front_apost.html", boards=boards)

    def post(self):
        form = AddPostForm(request.form)

        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)

            if not board:
                return restful.params_errors(message='没有这个板块')

            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            # return redirect(url_for('front.index'))
            return restful.success()
        else:
            return restful.params_errors(message=form.get_error())



front_bp.add_url_rule("/signup/", view_func=SignupView.as_view('signup'))
front_bp.add_url_rule("/signin/", view_func=SigninView.as_view('signin'))
front_bp.add_url_rule("/apost/", view_func=PostView.as_view('apost'))

Python全栈/Flask框架/bbs/templates/front/front_apost.html
{% extends 'front/front_base.html' %}

{% block title %}发布帖子{% endblock %}


{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
    <script src="{{ url_for('static',filename='front/js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='editormd/editormd.min.js') }}"></script>
    <script src="{{ url_for('static',filename='front/js/front_apost.js') }}"></script>
{% endblock %}


{% block main_content %}
<div class="main-container">
    <form action="" method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select name="board_id" class="form-control">
                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
     <div id="editor" class="form-group">
        <textarea name="content" id="TextContent" ></textarea>
     </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
</form>

<script type="text/javascript">
    var testEditor;

    $(function () {
        testEditor = editormd("editor", {
            width: "100%",
            height: 640,
            syncScrolling: "single",
            path: "{{ url_for('static',filename='editormd/lib/') }}",
            // 上传图片
            imageUpload : true,
            imageFormats : [ "jpg", "jpeg", "gif", "png", "bmp", "webp" ],
            // 上传图片时指定调用后台的视图函数
            imageUploadURL : "",

        });
    });
</script>
</div>
{% endblock %}

Python全栈/Flask框架/bbs/templates/front/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="{{ url_for('static', filename='front/css/front_index.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='front/css/front_base.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='common/sweetalert/sweetalert.css') }}">
    <script src="{{ url_for('static', filename='common/sweetalert/lgalert.js') }}"></script>
    <script src="{{ url_for('static', filename='common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ url_for('static', filename='common/lgajax.js') }}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">逻辑Python论坛</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">首页 <span class="sr-only">(current)</span></a></li>
                <!--<li><a href="#">Link</a></li>-->
                <!--<li class="dropdown">-->
                <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
                <!--<ul class="dropdown-menu">-->
                <!--<li><a href="#">Action</a></li>-->
                <!--<li><a href="#">Another action</a></li>-->
                <!--<li><a href="#">Something else here</a></li>-->
                <!--<li role="separator" class="divider"></li>-->
                <!--<li><a href="#">Separated link</a></li>-->
                <!--<li role="separator" class="divider"></li>-->
                <!--<li><a href="#">One more separated link</a></li>-->
                <!--</ul>-->
                <!--</li>-->
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">

                {% if g.front_user %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ g.front_user.username }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人中心</a></li>
                        <li><a href="#">设置</a></li>
                        <li><a href="#">退出登录</a></li>

                    </ul>
                </li>
                {% else %}
                    <li><a href="{{ url_for('front.signin') }}">登录</a></li>
                    <li><a href="{{ url_for('front.signup') }}">注册</a></li>
                {% endif %}


            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block main_content %}
<!--<div class="main-container">-->

<!--</div>-->
{% endblock %}

</body>
</html>

Python全栈/Flask框架/bbs/templates/front/front_index.html
{% extends 'front/front_base.html' %}

{% block title %}首页{% endblock %}

{% block main_content %}
<div class="main-container">
    <div class="lg-container">
        <div class="carousel slide" data-ride="carousel" id="carousel-example-generic">
            <!-- 指令 -->
            <ol class="carousel-indicators">
                <li class="active" data-slide-to="0" data-target="#carousel-example-generic"></li>
                <li data-slide-to="1" data-target="#carousel-example-generic"></li>
                <li data-slide-to="2" data-target="#carousel-example-generic"></li>
                <li data-slide-to="3" data-target="#carousel-example-generic"></li>
            </ol>

            <!-- 轮播图 -->
            <div class="carousel-inner" role="listbox">
                {% for banner in banners %}
                {% if loop.first %}
                <div class="item active">
                    {% else %}
                    <div class="item">
                        {% endif %}

                        <img alt="..." src="{{ banner.image_url }}" style="width: 300px;height: 300px;">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    {% endfor %}
                    <!--<div class="item">-->
                    <!--<img src="https://img.alicdn.com/simba/img/TB1Uwm2GkL0gK0jSZFxSutWHVXa.jpg" alt="...">-->
                    <!--<div class="carousel-caption">-->
                    <!--...-->
                    <!--</div>-->
                    <!--</div>-->
                </div>

                <!-- 左右切换 -->
                <a class="left carousel-control" data-slide="prev" href="#carousel-example-generic" role="button">
                    <span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" data-slide="next" href="#carousel-example-generic" role="button">
                    <span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="post-group">
                <ul class="post-group-head">
                    <li class=""><a href="#">最新</a></li>
                    <li class=""><a href="#">精华帖子</a></li>
                    <li class=""><a href="#">点赞最多</a></li>
                    <li class=""><a href="#">评论最多</a></li>
                </ul>
                <ul class="post-list-group">
                    {% for post in posts %}
                        <li>
                            <div class="author-avatar-group">
                                <img src="#" alt="">
                            </div>
                            <div class="post-info-group">
                                <p class="post-title">
                                    <a href="#">{{ post.title }}</a>
                                    <span class="label label-danger">精华帖</span>
                                </p>
                                <p class="post-info">
                                    <span>作者:{{ post.author.username }}</span>
                                    <span>发表时间:{{ post.create_time }}</span>
                                    <span>评论:0</span>
                                    <span>阅读:0</span>
                                </p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div style="text-align:center;">

                </div>
            </div>
        </div><!---->

        <div class="sm-container">
            <div style="padding-bottom:10px;">
                <a href="{{ url_for('front.apost') }}" class="btn btn-warning btn-block">发布帖子</a>
            </div>
            <div class="list-group">
                <a href="/" class="list-group-item active">所有板块</a>
                {% for board in boards %}

                    {% if current_board == board.id %}
                        <a href="{{ url_for('front.index', board_id=board.id) }}" class="list-group-item active">{{ board.name }}</a>
                    {% else %}
                        <a href="{{ url_for('front.index', board_id=board.id) }}" class="list-group-item">{{ board.name }}</a>
                    {% endif %}

                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}

Python全栈/Flask框架/bbs/templates/front/front_signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>论坛登录</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='front/css/front_signbase.css') }}" rel="stylesheet">
    <!--    <link href="../../static/front/css/front_signbase.css" rel="stylesheet">-->
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static',filename='common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ url_for('static',filename='common/sweetalert/lgalert.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='common/sweetalert/sweetalert.css') }}">
    <script src="{{ url_for('static', filename='front/js/front_signin.js') }}"></script>
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.js"></script>
</head>
<body>
    <div class="outer-box">
        <div class="logo-box">
            <a href="/">
                <img src="{{ url_for('static',filename='common/images/logo.png') }}"/>
            </a>
        </div>
        <h2 class="page-title">
           逻辑登录
        </h2>
        <div class="sign-box">
            <div class="form-group">
                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="密码">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="remember" value="1">记住我
                </label>
            </div>
            <div class="form-group">
                <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
            </div>
            <div class="form-group">
                <a href="{{ url_for('front.signup') }}" class="signup-link">没有账号？立即注册</a>
                <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
            </div>
        </div>
        <span style="display:none;" id="return-to-span">{{ return_to }}</span>
    </div>
</body>
</html> 
   

Python全栈/Flask框架/bbs/templates/front/front_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>论坛注册</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
   <!--<link href="css/front_signbase.css" rel="stylesheet">-->
   <link href="{{ url_for('static', filename='front/css/front_signbase.css') }}" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='front/js/front_signup.js') }}"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='common/sweetalert/sweetalert.css') }}">
    <script src="{{ url_for('static', filename='common/sweetalert/lgalert.js') }}"></script>
    <script src="{{ url_for('static', filename='common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.js"></script>
</head>
<body>
    <div class="outer-box">
        <div class="logo-box">
            <a href="/">
                <img src="{{ url_for('static',filename='common/images/logo.png') }}"/>
            </a>
        </div>
        <h2 class="page-title">逻辑论坛注册</h2>

        <div class="sign-box">
            <div class="form-group">
                <div class="input-group">
                    <input type="text" name="telephone" class="form-control" placeholder="手机号码">
                    <span class="input-group-btn">
                        <button class="btn btn-default" id="sms-captcha-btn">
                            发送验证码
                        </button>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <input type="text" name="sms_captcha" class="form-control" placeholder="短信验证码">
            </div>
            <div class="form-group">
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>
            <div class="form-group">
                <input type="password" name="password1" class="form-control" placeholder="密码">
            </div>
            <div class="form-group">
                <input type="password" name="password2" class="form-control" placeholder="确认密码">
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input type="text" name="graph_captcha" class="form-control" placeholder="图形验证码">

                    <span class="input-group-addon captcha-addon">
                        <img id="captcha-img" class="captcha-img" src="{{ url_for('front.graph_captcha') }}" alt="">
                    </span>
                </div>
            </div>
            <div class="form-group">
                <span style="display:none" id="return-to-span">{{ return_to }}</span>
                <button class="btn btn-warning btn-block" id="submit-btn">
                    立即注册
                </button>
            </div>
        </div>

    </div>
</body>
</html>

Python全栈/Flask框架/bbs/templates/front/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{{ url_for('front.signup') }}">注册测试跳转</a>
<a href="{{ url_for('front.signin') }}">登录测试跳转</a>
</body>
</html>