Python全栈/Django框架/Qywz(1)/Qywz/newsApp/urls.py
from django.contrib import admin
from django.urls import path,re_path    #导入re_path函数
from django.views.static import serve   #导入serve
from django.conf import settings        #导入settings
from django.conf.urls import include    #导入include函数
from newsApp import views

urlpatterns = [
    path('qyxw/<pageNo>',views.qyxw),
    path('addNews/',views.addNews),
    path('modNews/<id>',views.modNews),
    path('delNews/<id>/<curPageNo>',views.delNews),
    # path('upload',views.upload),
    re_path('media/(?P<path>.*)',serve,{'document_root':settings.MEDIA_ROOT}),
]

Python全栈/Django框架/Qywz(1)/Qywz/newsApp/models.py
from django.db import models

# Create your models here.
# 企业新闻 and 行业新闻
class news(models.Model):
    CHOICES = (('0','企业新闻'),('1','行业新闻'))
    id = models.AutoField(primary_key=True) # id，主键
    title = models.CharField(max_length=50) # 标题
    author = models.CharField(max_length=50) # 作者
    content = models.TextField() #新闻内容
    create_time = models.DateField(auto_now=True,null=True) # 发布日期
    classify = models.CharField(max_length=1,choices=CHOICES) #类别

# 通知公告
class notice(models.Model):
    id = models.AutoField(primary_key=True) # id，主键
    author = models.CharField(max_length=50) # 作者
    content = models.TextField() #通知内容
    create_time = models.DateField(auto_now=True,null=True) # 发布日期

Python全栈/Django框架/Qywz(1)/Qywz/newsApp/views.py
from django.shortcuts import render
from newsApp.models import news,notice
from django import forms
from django.core.paginator import Paginator
from django.shortcuts import redirect

# Create your views here.
def qyxw(request,pageNo):
    newss = news.objects.all()
    pages = Paginator(newss,5)
    page = pages.get_page(pageNo)
    d = {'page':page}
    t = 'qyxw.html'
    return render(request,t,d)

class addNewsModelForm(forms.ModelForm):
    # publisher = forms.ModelChoiceField(label='出版社',queryset=publisher.objects.all(),empty_label=None)
    class Meta:
        model = news
        fields = ['id','title','author','classify','content']
        labels = {'id':'ID','title':'标题','author':'作者','classify':'分类','content':'新闻内容'}
      
def addNews(request):
    if request.method == 'POST':
        mfrm = addNewsModelForm(request.POST,request.FILES)
        if mfrm.is_valid():
            mfrm.save()
            msg = '数据添加成功!'
        else:
            msg = '数据校验未通过！'
    else:
        mfrm = addNewsModelForm()
        msg = '请输入新闻数据！'
    t = 'news.html'
    d = {'title':'添加新闻信息','url':'/news/addNews/','id':'','form':mfrm,'msg':msg}
    return render(request,t,d)

class modNewsModelForm(addNewsModelForm):
    id = forms.CharField(label='id',widget=forms.TextInput(attrs={'readonly':'readonly'}))

def modNews(request,id):
    xw = news.objects.get(id=id)
    if request.method == 'POST':
        mfrm = modNewsModelForm(request.POST,request.FILES,instance=xw)
        if mfrm.is_valid():
            mfrm.save()
            msg = '数据修改成功！'
        else:
            msg = '数据校验未通过！'
    else:
        mfrm = modNewsModelForm(instance=xw)
        msg = '请修改新闻数据！'
    t = 'news.html'
    d = {'title':'修改书本信息','url':'/news/modNews/','id':id,'form':mfrm,'msg':msg}
    return render(request,t,d)

def delNews(request,id,curPageNo):
    news.objects.get(id=id).delete()
    return redirect(qyxw,pageNo=curPageNo)

Python全栈/Django框架/Qywz(1)/Qywz/newsApp/templates/news.html
{% extends 'backbase.html' %} {% load static %} {% block header %}
<!-- 在这里编写自己的css和js -->
<link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'build/jodit.min.css' %}">
<script src="{% static 'build/jodit.min.js' %}"></script>
<style>
    .form-group {
        text-align: center !important;
    }
</style>
{% endblock %} {% block content %}

<h1>{{title}}</h1>
<form action="{{url}}{{id}}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <div class="form-group">
        <input type="submit" class="btn btn-default" value="提交"></input>
    </div>
</form>
<p>
    {{msg}}
</p>
<p>
    <a href="/news/qyxw/1">企业新闻列表</a>
</p>
<script>
    var editor = new Jodit('#id_content', {
        zIndex: 10,
        language: 'zh_cn',
        width: 'auto',
        height: 'auto',
        minHeight: 300,
        saveModeInCookie: false,
        iframeStyle: '*,.jodit_wysiwyg {color:red;}',
        observer: {
            timeout: 800
        },
        uploader: {
            url: "/news/upload",
            insertImageAsBase64URI: false,
            imagesExtensions: [
                "jpg",
                "png",
                "jpeg",
                "gif"
            ],
            //headers: {"token":`${db.token}`},
            filesVariableName: function(t) {
                return "files[" + t + "]"
            }, //"files",
            withCredentials: false,
            pathVariableName: "path",
            format: "json",
            method: "POST",
            prepareData: function(formdata) {
                file = formdata.getAll("files[0]")[0];
                //formdata.append("createTime", (Date.now() / 1000) | 0);
                formdata.append("file", file);
                return formdata;
            },
            isSuccess: function(e) {
                console.log(e);
                //console.log("shuju"+e.length);
                return e.data;
            },
            getMessage: function(e) {
                return void 0 !== e.data.messages && Array.isArray(e.data.messages) ? e.data.messages.join("") : ""
            },
            process: function(resp) {
                var ss = this;
                console.log(resp);
                var arrfile = [];
                arrfile.unshift(resp.data);
                console.log(arrfile.length + "||路径：" + arrfile[0]);
                console.log("再次打印：" + resp.data + "||baseurl:");
                return {
                    files: arrfile, //[this.options.uploader.filesVariableName] || [],
                    path: '',
                    baseurl: '',
                    error: resp.msg,
                    msg: resp.msg,
                    isImages: arrfile,
                };
                //return resp.data;
            },
            error: function(e) {
                this.jodit.events.fire("errorMessage", e.message, "error", 4e3)
            },
            defaultHandlerError: function(e) {
                this.jodit.events.fire("errorMessage", e.message)
            },
            contentType: function(e) {
                return (void 0 === this.jodit.ownerWindow.FormData || "string" == typeof e) &&
                    "application/x-www-form-urlencoded; charset=UTF-8"
            }
        },
    });
</script>
{% endblock %}

Python全栈/Django框架/Qywz(1)/Qywz/newsApp/templates/qyxw.html
{% extends 'backbase.html' %}
{% load static %}
{% block header %}
<!-- 在这里编写自己的css和js -->
<link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
{% endblock %} {% block content %}
<h1 class="bg-success" style="text-align:center;">新闻列表</h1>
<table class="table table-bordered table-condensed">
    <tr>
        <th>ID</th>
        <th>标题</th>
        <th>作者</th>
        <th>文章内容</th>
        <th>发布日期</th>
        <th>类型</th>
        <th>操作</th>
    </tr>
    {% for news in page %}
    <tr style="background-color:{% cycle 'white' 'lavender' %};">
        <td>{{news.id}}</td>
        <td>{{news.title}}</td>
        <td>{{news.author}}</td>
        <td>{{news.content}}</td>
        <td>{{news.create_time|date:'Y-m-d'}}</td>
        <td>{{news.get_classify_display}}</td>
        <td>
            <a href="/news/modNews/{{news.id}}" onclick="return confirm('确认删除该记录吗？');">修改</a>|
            <a href="/news/delNews/{{news.id}}/{{page.number}}" onclick="return confirm('确认删除该记录吗？');">删除</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% if page.has_previous %} |
<a href="/news/qyxw/1">第一页</a> |
<a href="/news/qyxw/{{page.previous_page_number}}">上一页</a> {% endif %}
|当前页码：{{page.number}}/{{page.paginator.num_pages}}| {% if page.has_next %}
<a href="/news/qyxw/{{page.next_page_number}}">下一页</a> |
<a href="/news/qyxw/{{page.paginator.num_pages}}">最末页</a>| {% endif %}
<hr>
<p><a href="/news/addNews/">添加新闻</a></p>
{% endblock %}