Python全栈/Flask框架/bbs/apps/cms/models.py
# @ Time    : 2020/5/8 21:27
# @ Author  : JuRan

from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class CMSPersmission(object):
    # 255二进制来表示所有的权限
    ALL_PERMISSION  = 0b11111111

    # 访问权限
    VISITOR         = 0b00000001

    # 管理帖子权限
    POSTER          = 0b00000010

    # 管理评论
    COMMENTER       = 0b00000100

    # 管理板块
    BOARDER         = 0b00001000

    # 管理前台用户
    FRONTUSER       = 0b00010000

    # 管理后台用户
    CMSUSER         = 0b00100000

    # 管理管理员用户
    ADMINER         = 0b01000000


cms_role_user = db.Table(
    'cms_role_user',
    db.Column('cms_role_id', db.Integer, db.ForeignKey('cms_role.id'), primary_key=True),
    db.Column('cms_user_id', db.Integer, db.ForeignKey('cms_user.id'), primary_key=True),
)


# 角色
class CMSRole(db.Model):
    __tablename__ = 'cms_role'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    desc = db.Column(db.String(200), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    permissions = db.Column(db.Integer, default=CMSPersmission.VISITOR)

    users = db.relationship('CMSUser', secondary=cms_role_user, backref='roles')



class CMSUser(db.Model):
    __tablename__ = 'cms_user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)
    join_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, username, password, email):
        self.username = username
        self.password = password
        self.email = email

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        result = check_password_hash(self.password, raw_password)
        return result

    @property
    def permissions(self):
        if not self.roles:
            return 0
        all_permissions = 0
        for role in self.roles:
            permissions = role.permissions
            # 获取角色的所有的权限
            all_permissions |= permissions

        return all_permissions

    # CMSPersmission.VISITOR
    def has_permission(self, permission):

        all_permissions = self.permissions
        # 0b11111111    用户的权限 0b00001000
        # 0b00000001  permission
        result = all_permissions & permission == permission
        return result

    @property
    def is_developer(self):
        return self.has_permission(CMSPersmission.ALL_PERMISSION)


class BannerModel(db.Model):
    __tablename__ = 'banner'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(255), nullable=False)
    # 图片链接
    image_url = db.Column(db.String(255), nullable=False)
    # 跳转链接
    link_url = db.Column(db.String(255), nullable=False)
    priority = db.Column(db.Integer, default=0)
    create_time = db.Column(db.DateTime, default=datetime.now)
    # 1 未删除  0 删除
    is_delete = db.Column(db.Integer, default=1)


class BoardModel(db.Model):
    __tablename__ = 'cms_board'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(255), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)

Python全栈/Flask框架/bbs/apps/cms/forms.py
# @ Time    : 2020/5/8 21:27
# @ Author  : JuRan

from wtforms import Form, StringField, IntegerField, ValidationError
from wtforms.validators import Email, InputRequired, Length, EqualTo, URL
from utils import lgcache



class BaseForm(Form):
    def get_error(self):
        message = self.errors.popitem()[1][0]
        return message

#
class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='请出入正确的邮箱地址'), InputRequired(message='请输入邮箱')])
    password = StringField(validators=[Length(6, 20, message='请输入正确格式的密码')])
    remember = IntegerField()


# 表单提交上来的数据 是否符合要求
class ResetPwdForm(BaseForm):
    oldpwd = StringField(validators=[Length(6, 20, message='密码长度有误')])
    newpwd = StringField(validators=[Length(6, 20, message='密码长度有误')])
    # 两次密码输入是否一致
    newpwd2 = StringField(validators=[EqualTo("newpwd", message="两次密码输入不一致")])


class ResetEmailForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确的邮箱格式')])
    captcha = StringField(validators=[Length(min=4, max=4, message='请输入正确长度的验证码')])


    def validate_captcha(self, field):
        # 表单提交上的验证码
        captcha = self.captcha.data
        email = self.email.data

        # 取redis中保存的验证码
        redis_captcha = lgcache.redis_get(email)

        if not redis_captcha or captcha.lower() != redis_captcha.lower():
            raise ValidationError('邮箱验证码错误')


class AddBannerForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入轮播图名称')])
    image_url = StringField(validators=[InputRequired(message='请输入图片链接'), URL(message='图片链接有误')])
    link_url = StringField(validators=[InputRequired(message='请输入跳转链接'), URL(message='图片链接有误')])
    priority = IntegerField(validators=[InputRequired(message='请输入轮播图优先级')])



class UpdateBannerForm(AddBannerForm):
    banner_id = IntegerField(validators=[InputRequired(message='轮播图不存在')])


class AddBoardForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入板块名称')])


class UpdateBoardForm(AddBoardForm):
    board_id = StringField(validators=[InputRequired(message='请输入板块ID')])

Python全栈/Flask框架/bbs/apps/cms/__init__.py
# @ Time    : 2020/5/8 21:26
# @ Author  : JuRan

Python全栈/Flask框架/bbs/apps/cms/views.py
# @ Time    : 2020/5/8 21:27
# @ Author  : JuRan

from flask import (
    Blueprint,
    render_template,
    views,
    request,
    redirect,
    url_for,
    session,
    jsonify,
    g
)

from apps.cms.forms import (
    LoginForm,
    ResetPwdForm,
    ResetEmailForm,
    AddBannerForm,
    UpdateBannerForm,
    AddBoardForm,
    UpdateBoardForm
)
from apps.cms.models import CMSUser, CMSPersmission, BannerModel, BoardModel
from apps.front.models import PostModel
from exts import db, mail
from utils import restful, random_captcha, lgcache
from flask_mail import Message

from .decorators import login_required, permission_required

cms_bp = Blueprint("cms", __name__, url_prefix='/cms')
from .hooks import before_request


@cms_bp.route("/")
# @login_required
def index():
    # print(session.get('user_id'))
    # return "cms index"
    return render_template("cms/cms_index.html")


@cms_bp.route('/logout/')
def logout():
    # 删除session  user_id
    # 重定向 登录页面
    del session['user_id']
    return redirect(url_for('cms.login'))


# @cms_bp.route('/test/')
# def demo():
#     return "测试是否可以访问"

@cms_bp.route("/profile/")
def profile():
    return render_template("cms/cms_profile.html")


class LoginView(views.MethodView):

    def get(self, message=None):
        return render_template('cms/cms_login.html', message=message)

    def post(self):
        login_form = LoginForm(request.form)
        if login_form.validate():
            # 数据库验证
            email = login_form.email.data
            password = login_form.password.data
            remember = login_form.remember.data
            user = CMSUser.query.filter_by(email=email).first()
            # 验证用户是否存在  以及密码是否正确
            if user and user.check_password(password):
                session['user_id'] = user.id
                if remember:
                    session.permanent = True
                # 登录成功 跳转首页
                return redirect(url_for('cms.index'))
            else:
                # render_template('cms/cms_login.html', message="邮箱或者密码错误")
                return self.get(message="邮箱或者密码错误")
        else:
            # print(login_form.errors.popitem()[1][0])
            # message = login_form.errors.popitem()[1][0]
            # return "表单验证错误"
            return self.get(message=login_form.get_error())


class ResetPwdView(views.MethodView):

    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        form = ResetPwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            # 对象
            user = g.cms_user
            # 用户提交的数据 juran 密码 是否和数据库中一直
            if user.check_password(oldpwd):
                # 更新我的密码
                user.password = newpwd
                db.session.commit()
                # return jsonify({"code": 200, "message": ""})
                return restful.success()
            else:
                # return jsonify({"code": 400, "message": "旧密码错误"})
                return restful.params_errors(message="旧密码错误")
        else:
            # ajax json类型的数据
            # message = form.errors.popitem()[1][0]
            # return jsonify({"code": 400, "message": message})
            return restful.params_errors(message=form.get_error())


class ResetEmailView(views.MethodView):

    def get(self):
        return render_template('cms/cms_resetemail.html')

    def post(self):
        form = ResetEmailForm(request.form)
        if form.validate():
            email = form.email.data
            # 查询数据库
            # CMSUser.query.filter_by(email=email).first()
            # CMSUser.query.filter(CMSUser.email==email).first()

            g.cms_user.email = email
            db.session.commit()
            return restful.success()

        else:
            return restful.params_errors(form.get_error())


# 发送邮件
@cms_bp.route("/send_mail/")
def send_mail():
    message = Message('邮件发送', recipients=['2705185834@qq.com'], body='测试邮件发送')
    mail.send(message)
    return '邮件已发送'


# 邮件发送
class EmailCaptcha(views.MethodView):
    def get(self):
        email = request.args.get('email')
        if not email:
            return restful.params_errors('请传递邮箱参数')

        # 发送邮件  内容发送一个验证码 4 6 数字和英文组合
        captcha = random_captcha.get_random_captcha(4)
        message = Message('逻辑论坛邮箱验证码', recipients=[email], body='您的验证码是 %s' % captcha)
        try:
            mail.send(message)
        except:
            return restful.server_errors()

        # 验证码 保存下来 MySQL 过期时间  Redis 效率  key email value captcha
        lgcache.redis_set(email, captcha)
        return restful.success()


@cms_bp.route("/posts/")
@permission_required(CMSPersmission.POSTER)
def posts():
    posts = PostModel.query.all()
    return render_template("cms/cms_posts.html", posts=posts)


@cms_bp.route("/comments/")
@permission_required(CMSPersmission.COMMENTER)
def comments():
    return render_template("cms/cms_comments.html")


@cms_bp.route("/boards/")
@permission_required(CMSPersmission.BOARDER)
def boards():
    boards = BoardModel.query.all()

    return render_template("cms/cms_boards.html", boards=boards)


@cms_bp.route("/aboard/", methods=['POST'])
@permission_required(CMSPersmission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_errors(message=form.get_error())


@cms_bp.route("/uboard/", methods=['POST'])
@permission_required(CMSPersmission.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data

        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.params_errors(message='没有这个分类')
    else:
        return restful.params_errors(message=form.get_error())


@cms_bp.route("/dboard/", methods=['POST'])
@permission_required(CMSPersmission.BOARDER)
def dboard():
    board_id = request.form.get('board_id')

    if not board_id:
        return restful.params_errors(message='分类不存在')

    board = BoardModel.query.get(board_id)

    if not board:
        return restful.params_errors(message='分类不存在')

    db.session.delete(board)
    db.session.commit()
    return restful.success()


@cms_bp.route("/fusers/")
def fusers():
    return render_template("cms/cms_fusers.html")


@cms_bp.route("/cusers/")
def cusers():
    return render_template("cms/cms_cusers.html")


@cms_bp.route("/croles/")
def croles():
    return render_template("cms/cms_croles.html")


@cms_bp.route("/banners/")
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template("cms/cms_banners.html", banners=banners)


# 添加
@cms_bp.route("/abanner/", methods=['POST'])
def abanner():
    form = AddBannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data

        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_errors(message=form.get_error())


# 修改
@cms_bp.route("/ubanner/", methods=['POST'])
def ubanner():
    # 修改  banner_id
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_errors(message='轮播图不存在')
    else:
        return restful.params_errors(message=form.get_error())


# 删除
@cms_bp.route('/dbanner/', methods=['POST'])
def dbanner():
    # post方式
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.params_errors(message='轮播图不存在')

    banner = BannerModel.query.get(banner_id)
    if banner:
        db.session.delete(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_errors('轮播图不存在')


cms_bp.add_url_rule("/login/", view_func=LoginView.as_view('login'))
cms_bp.add_url_rule("/resetpwd/", view_func=ResetPwdView.as_view('resetpwd'))
cms_bp.add_url_rule("/resetemail/", view_func=ResetEmailView.as_view('resetemail'))
cms_bp.add_url_rule("/email_captcha/", view_func=EmailCaptcha.as_view('email_captcha'))

Python全栈/Flask框架/bbs/templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}

{% block title %}
轮播图管理
{% endblock %}

{% block head %}
<script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
<script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
<script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
<script src="{{ url_for('static', filename='common/lgqiniu.js') }}"></script>
<script src="{{ url_for('static',filename='cms/js/banners.js') }}"></script>
<style>
    .top-box button{
        float: right;
    }
</style>
{% endblock %}

{% block page_title %}
{{ self.title() }}
{% endblock %}

{% block content %}


<div class="top-box">
    <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>名称</th>
        <th>图片链接</th>
        <th>跳转链接</th>
        <th>优先级</th>
        <th>创建时间</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for banner in banners %}
        <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}"
            data-priority="{{ banner.priority }}" data-id="{{ banner.id }}">
            <td>{{ banner.name }}</td>
            <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url|truncate(length=20) }}</a></td>
            <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
            <td>{{ banner.priority }}</td>
            <td>{{ banner.create_time }}</td>
            <td>
                <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">轮播图</h4>
            </div>
            <div class="modal-body">
                <form action="" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">名称：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">图片：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                        </div>
                        <button class="btn btn-info col-sm-2" id="upload-btn">添加图片</button>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">跳转：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">权重：</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control" name="priority" placeholder="优先级">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Python全栈/Flask框架/bbs/templates/cms/cms_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='cms/css/cms_base.css') }}">
    <script src="{{ url_for('static', filename='cms/js/cms_base.js') }}"></script>
    <!-- 提示框资源文件 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='common/sweetalert/sweetalert.css') }}">
    <script src="{{ url_for('static', filename='common/sweetalert/lgalert.js') }}"></script>
    <script src="{{ url_for('static', filename='common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ url_for('static', filename='common/lgajax.js') }}"></script>

    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">逻辑课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{{ g.cms_user.username }}</a></li>
                <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="#">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>
                {% set user = g.cms_user %}
                <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                {% if user.has_permission(CMSPersmission.POSTER) %}
                <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                {% endif %}

                {% if user.has_permission(CMSPersmission.COMMENTER) %}
                <li class="comments-manage"><a href="#">评论管理</a></li>
                {% endif %}
                {% if user.has_permission(CMSPersmission.BOARDER) %}
                <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                {% endif %}

                {% if user.has_permission(CMSPersmission.FRONTUSER) %}
                <li class="nav-group user-manage"><a href="#">前台用户管理</a></li>
                {% endif %}

                {% if user.has_permission(CMSPersmission.CMSUSER) %}
                <li class="nav-group cmsuser-manage"><a href="#">CMS用户管理</a></li>
                {% endif %}

                {% if user.is_developer %}
                <li class="cmsrole-manage"><a href="#">CMS组管理</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %} {% endblock %}</h1>
            <div class="main_content">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

Python全栈/Flask框架/bbs/templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}

{% block title %}
板块管理
{% endblock %}

{% block page_title %}
{{ self.title() }}
{% endblock %}

{% block head %}
<script src="{{ url_for('static', filename='cms/js/boards.js') }}"></script>
{% endblock %}

{% block content %}
<div class="top-box">
    <button class="btn btn-warning" style="float:right;" id="add-board-btn">添加新板块</button>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>板块名称</th>
        <th>帖子数量</th>
        <th>创建时间</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for board in boards %}
        <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
            <td>{{ board.name }}</td>
            <td>0</td>
            <td>{{ board.create_time }}</td>
            <td>
                <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

Python全栈/Flask框架/bbs/templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    评论管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block content %}
    评论管理
{% endblock %}

Python全栈/Flask框架/bbs/templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    后台用户组管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block content %}
    后台用户组管理
{% endblock %}

Python全栈/Flask框架/bbs/templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    后台用户管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block content %}
    后台用户管理
{% endblock %}

Python全栈/Flask框架/bbs/templates/cms/cms_fusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    前台用户管理
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block content %}
    前台用户管理
{% endblock %}

Python全栈/Flask框架/bbs/templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    逻辑CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到逻辑CMS管理系统
{% endblock %}


{% block content %}
    {{ self.page_title() }}
{% endblock %}

Python全栈/Flask框架/bbs/templates/cms/cms_login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">


    <title>CMS登录</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='cms/css/signin.css') }}" rel="stylesheet">


  </head>

  <body>

    <div class="container">

      <form class="form-signin" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <h2 class="form-signin-heading">请登录</h2>
        <label for="inputEmail" class="sr-only">邮箱</label>
        <input type="email" id="inputEmail" name="email" class="form-control" placeholder="邮箱地址" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="填写密码" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="1" name="remember"> 记住我
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">立即登录</button>
      </form>
      {% if message %}
        <p style="text-align:center" class="text-danger">{{ message }}</p>
      {% endif %}

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>